export const utBringUpHalf: string;
export const utBringUp1: string;
export const utBringUp2: string;
export const utBringUp3: string;
export const utBringUp4: string;
export const utBringUp5: string;
export const utBringNeutral: string;
export const utBringBack1: string;
export const utBringBack2: string;
